"""Theme system for codesm TUI - 30+ themes inspired by OpenCode"""

from textual.theme import Theme

# Theme definitions organized by category
THEME_DEFINITIONS = {
    "Dark": [
        {
            "name": "dark",
            "display": "Dark",
            "primary": "#3d4550",
            "secondary": "#5dd9c1",
            "accent": "#5dd9c1",
            "foreground": "#d4d4d4",
            "background": "#0d1117",
            "surface": "#161b22",
            "panel": "#21262d",
            "success": "#3fb950",
            "warning": "#d29922",
            "error": "#f85149",
        },
        {
            "name": "github-dark",
            "display": "GitHub Dark",
            "primary": "#30363d",
            "secondary": "#58a6ff",
            "accent": "#58a6ff",
            "foreground": "#c9d1d9",
            "background": "#0d1117",
            "surface": "#161b22",
            "panel": "#21262d",
            "success": "#3fb950",
            "warning": "#d29922",
            "error": "#f85149",
        },
        {
            "name": "dracula",
            "display": "Dracula",
            "primary": "#6272a4",
            "secondary": "#8be9fd",
            "accent": "#ff79c6",
            "foreground": "#f8f8f2",
            "background": "#282a36",
            "surface": "#2d303d",
            "panel": "#343746",
            "success": "#50fa7b",
            "warning": "#ffb86c",
            "error": "#ff5555",
        },
        {
            "name": "monokai",
            "display": "Monokai",
            "primary": "#75715e",
            "secondary": "#a6e22e",
            "accent": "#f92672",
            "foreground": "#f8f8f2",
            "background": "#272822",
            "surface": "#2d2e27",
            "panel": "#3e3d32",
            "success": "#a6e22e",
            "warning": "#fd971f",
            "error": "#f92672",
        },
        {
            "name": "nord",
            "display": "Nord",
            "primary": "#4c566a",
            "secondary": "#88c0d0",
            "accent": "#81a1c1",
            "foreground": "#d8dee9",
            "background": "#2e3440",
            "surface": "#3b4252",
            "panel": "#434c5e",
            "success": "#a3be8c",
            "warning": "#ebcb8b",
            "error": "#bf616a",
        },
        {
            "name": "tokyo-night",
            "display": "Tokyo Night",
            "primary": "#565f89",
            "secondary": "#7aa2f7",
            "accent": "#bb9af7",
            "foreground": "#a9b1d6",
            "background": "#1a1b26",
            "surface": "#1f2335",
            "panel": "#24283b",
            "success": "#9ece6a",
            "warning": "#e0af68",
            "error": "#f7768e",
        },
        {
            "name": "one-dark",
            "display": "One Dark",
            "primary": "#5c6370",
            "secondary": "#61afef",
            "accent": "#c678dd",
            "foreground": "#abb2bf",
            "background": "#1e1e2e",
            "surface": "#282c34",
            "panel": "#21252b",
            "success": "#98c379",
            "warning": "#e5c07b",
            "error": "#e06c75",
        },
        {
            "name": "gruvbox-dark",
            "display": "Gruvbox Dark",
            "primary": "#665c54",
            "secondary": "#b8bb26",
            "accent": "#fabd2f",
            "foreground": "#ebdbb2",
            "background": "#282828",
            "surface": "#32302f",
            "panel": "#3c3836",
            "success": "#b8bb26",
            "warning": "#fabd2f",
            "error": "#fb4934",
        },
        {
            "name": "catppuccin-mocha",
            "display": "Catppuccin Mocha",
            "primary": "#6c7086",
            "secondary": "#89b4fa",
            "accent": "#cba6f7",
            "foreground": "#cdd6f4",
            "background": "#1e1e2e",
            "surface": "#181825",
            "panel": "#313244",
            "success": "#a6e3a1",
            "warning": "#f9e2af",
            "error": "#f38ba8",
        },
        {
            "name": "catppuccin-macchiato",
            "display": "Catppuccin Macchiato",
            "primary": "#6e738d",
            "secondary": "#8aadf4",
            "accent": "#c6a0f6",
            "foreground": "#cad3f5",
            "background": "#24273a",
            "surface": "#1e2030",
            "panel": "#363a4f",
            "success": "#a6da95",
            "warning": "#eed49f",
            "error": "#ed8796",
        },
        {
            "name": "solarized-dark",
            "display": "Solarized Dark",
            "primary": "#586e75",
            "secondary": "#268bd2",
            "accent": "#2aa198",
            "foreground": "#839496",
            "background": "#002b36",
            "surface": "#073642",
            "panel": "#094554",
            "success": "#859900",
            "warning": "#b58900",
            "error": "#dc322f",
        },
        {
            "name": "ayu-dark",
            "display": "Ayu Dark",
            "primary": "#5c6773",
            "secondary": "#39bae6",
            "accent": "#ffb454",
            "foreground": "#bfbdb6",
            "background": "#0d1017",
            "surface": "#131721",
            "panel": "#1a1f29",
            "success": "#7fd962",
            "warning": "#ffb454",
            "error": "#d95757",
        },
        {
            "name": "material-dark",
            "display": "Material Dark",
            "primary": "#546e7a",
            "secondary": "#82aaff",
            "accent": "#c792ea",
            "foreground": "#eeffff",
            "background": "#212121",
            "surface": "#263238",
            "panel": "#2f3d44",
            "success": "#c3e88d",
            "warning": "#ffcb6b",
            "error": "#f07178",
        },
        {
            "name": "synthwave",
            "display": "Synthwave '84",
            "primary": "#614d85",
            "secondary": "#36f9f6",
            "accent": "#ff7edb",
            "foreground": "#ffffff",
            "background": "#2b213a",
            "surface": "#34294f",
            "panel": "#3d3063",
            "success": "#72f1b8",
            "warning": "#fede5d",
            "error": "#fe4450",
        },
        {
            "name": "cyberpunk",
            "display": "Cyberpunk",
            "primary": "#4d4d4d",
            "secondary": "#00ff9f",
            "accent": "#ff00ff",
            "foreground": "#00ff9f",
            "background": "#000000",
            "surface": "#0d0d0d",
            "panel": "#1a1a1a",
            "success": "#00ff9f",
            "warning": "#ffff00",
            "error": "#ff0055",
        },
        {
            "name": "midnight",
            "display": "Midnight",
            "primary": "#3d4556",
            "secondary": "#7aa2f7",
            "accent": "#7dcfff",
            "foreground": "#a9b1d6",
            "background": "#0f0f14",
            "surface": "#16161e",
            "panel": "#1a1b26",
            "success": "#73daca",
            "warning": "#ff9e64",
            "error": "#f7768e",
        },
        {
            "name": "night-owl",
            "display": "Night Owl",
            "primary": "#5f7e97",
            "secondary": "#82aaff",
            "accent": "#c792ea",
            "foreground": "#d6deeb",
            "background": "#011627",
            "surface": "#021d34",
            "panel": "#0b2942",
            "success": "#addb67",
            "warning": "#ecc48d",
            "error": "#ef5350",
        },
        {
            "name": "palenight",
            "display": "Palenight",
            "primary": "#676e95",
            "secondary": "#82aaff",
            "accent": "#c792ea",
            "foreground": "#a6accd",
            "background": "#292d3e",
            "surface": "#2f3344",
            "panel": "#3a3f54",
            "success": "#c3e88d",
            "warning": "#ffcb6b",
            "error": "#f07178",
        },
        {
            "name": "horizon",
            "display": "Horizon",
            "primary": "#6c6f93",
            "secondary": "#e95678",
            "accent": "#fab795",
            "foreground": "#d5d8da",
            "background": "#1c1e26",
            "surface": "#232530",
            "panel": "#2e303e",
            "success": "#29d398",
            "warning": "#fac29a",
            "error": "#e95678",
        },
        {
            "name": "vesper",
            "display": "Vesper",
            "primary": "#5c5c5c",
            "secondary": "#ffc799",
            "accent": "#ffc799",
            "foreground": "#d4d4d4",
            "background": "#101010",
            "surface": "#1a1a1a",
            "panel": "#232323",
            "success": "#a3be8c",
            "warning": "#ffc799",
            "error": "#f07171",
        },
    ],
    "Light": [
        {
            "name": "light",
            "display": "Light",
            "primary": "#57606a",
            "secondary": "#0969da",
            "accent": "#0969da",
            "foreground": "#24292f",
            "background": "#ffffff",
            "surface": "#f6f8fa",
            "panel": "#eaeef2",
            "success": "#1a7f37",
            "warning": "#9a6700",
            "error": "#cf222e",
        },
        {
            "name": "github-light",
            "display": "GitHub Light",
            "primary": "#57606a",
            "secondary": "#0969da",
            "accent": "#8250df",
            "foreground": "#24292f",
            "background": "#ffffff",
            "surface": "#f6f8fa",
            "panel": "#eaeef2",
            "success": "#1a7f37",
            "warning": "#9a6700",
            "error": "#cf222e",
        },
        {
            "name": "solarized-light",
            "display": "Solarized Light",
            "primary": "#93a1a1",
            "secondary": "#268bd2",
            "accent": "#2aa198",
            "foreground": "#657b83",
            "background": "#fdf6e3",
            "surface": "#eee8d5",
            "panel": "#e4dcc8",
            "success": "#859900",
            "warning": "#b58900",
            "error": "#dc322f",
        },
        {
            "name": "catppuccin-latte",
            "display": "Catppuccin Latte",
            "primary": "#9ca0b0",
            "secondary": "#1e66f5",
            "accent": "#8839ef",
            "foreground": "#4c4f69",
            "background": "#eff1f5",
            "surface": "#e6e9ef",
            "panel": "#dce0e8",
            "success": "#40a02b",
            "warning": "#df8e1d",
            "error": "#d20f39",
        },
        {
            "name": "one-light",
            "display": "One Light",
            "primary": "#a0a1a7",
            "secondary": "#4078f2",
            "accent": "#a626a4",
            "foreground": "#383a42",
            "background": "#fafafa",
            "surface": "#f0f0f0",
            "panel": "#e5e5e5",
            "success": "#50a14f",
            "warning": "#c18401",
            "error": "#e45649",
        },
        {
            "name": "gruvbox-light",
            "display": "Gruvbox Light",
            "primary": "#928374",
            "secondary": "#79740e",
            "accent": "#b57614",
            "foreground": "#3c3836",
            "background": "#fbf1c7",
            "surface": "#f2e5bc",
            "panel": "#ebdbb2",
            "success": "#79740e",
            "warning": "#b57614",
            "error": "#9d0006",
        },
        {
            "name": "ayu-light",
            "display": "Ayu Light",
            "primary": "#8a9199",
            "secondary": "#55b4d4",
            "accent": "#f2ae49",
            "foreground": "#575f66",
            "background": "#fafafa",
            "surface": "#f0f0f0",
            "panel": "#e6e6e6",
            "success": "#86b300",
            "warning": "#f2ae49",
            "error": "#f51818",
        },
    ],
    "High Contrast": [
        {
            "name": "high-contrast-dark",
            "display": "High Contrast Dark",
            "primary": "#ffffff",
            "secondary": "#00ffff",
            "accent": "#ff00ff",
            "foreground": "#ffffff",
            "background": "#000000",
            "surface": "#0a0a0a",
            "panel": "#141414",
            "success": "#00ff00",
            "warning": "#ffff00",
            "error": "#ff0000",
        },
        {
            "name": "high-contrast-light",
            "display": "High Contrast Light",
            "primary": "#000000",
            "secondary": "#0000cc",
            "accent": "#cc00cc",
            "foreground": "#000000",
            "background": "#ffffff",
            "surface": "#f5f5f5",
            "panel": "#ebebeb",
            "success": "#006600",
            "warning": "#cc6600",
            "error": "#cc0000",
        },
    ],
}


def _create_theme(definition: dict, dark: bool = True) -> Theme:
    """Create a Theme from a definition dict"""
    return Theme(
        name=f"codesm-{definition['name']}",
        primary=definition["primary"],
        secondary=definition["secondary"],
        accent=definition["accent"],
        foreground=definition["foreground"],
        background=definition["background"],
        surface=definition["surface"],
        panel=definition["panel"],
        success=definition["success"],
        warning=definition["warning"],
        error=definition["error"],
        dark=dark,
        variables={
            "modal-bg": definition["surface"],
            "highlight": definition["secondary"],
            "muted": definition["primary"],
            "text-muted": definition["primary"],
            "input-bg": definition["background"],
            "border-color": definition["primary"],
        },
    )


# Build THEMES dict with all themes
THEMES = {}
THEME_LIST = []  # Ordered list for cycling

for category, definitions in THEME_DEFINITIONS.items():
    is_dark = category != "Light"
    for definition in definitions:
        theme = _create_theme(definition, dark=is_dark)
        THEMES[definition["name"]] = theme
        THEME_LIST.append({
            "name": definition["name"],
            "display": definition["display"],
            "category": category,
        })

THEME_NAMES = [t["name"] for t in THEME_LIST]


def get_next_theme(current: str) -> str:
    """Get the next theme in the rotation"""
    try:
        idx = THEME_NAMES.index(current)
        return THEME_NAMES[(idx + 1) % len(THEME_NAMES)]
    except ValueError:
        return THEME_NAMES[0]


def get_theme_display_name(name: str) -> str:
    """Get the display name for a theme"""
    for t in THEME_LIST:
        if t["name"] == name:
            return t["display"]
    return name.title()
